### ISSUE TITLE
React Native interface localization 

### ISSUE THREAD

**Issue by felix-zg** [thegrizzlylabs/geniusscan-sdk-demo#16]
Hello :) 

I didn't find any option to change the language of the scanning interface in the SDK API.
Also changing the phone language didn't work :( 

Any suggestions? :)

**Comment by guillaume-tgl** [comment]
The SDK is localized in 20 languages and should change its language to the device language as long as your app supports this language. Is your app localised? Do you have this issue on Android or iOS?

**Comment by felix-zg** [comment]
Thanks for your quick response! 

I checked on iOS. The app is localized but only it react-native based. 
Can I set the language from the SDK? :)

**Comment by guillaume-tgl** [comment]
You probably only have the localization enabled at the ReactNative level. To enable it at the iOS level, open the iOS project from the file at `ios/yourapp.xcworkspace` and use this screenshot to add languages: https://github.com/react-native-community/react-native-localize#add-projects-supported-localizations-ios

**Comment by felix-zg** [comment]
It works, thanks!
Also, an option to set the language from the SDK can be really lovely in the future :)
