### ISSUE TITLE
symbol(s) not found for architecture armv7

### ISSUE THREAD

**Issue by felix-zg** [thegrizzlylabs/geniusscan-sdk-demo#18]
Hello,

When we try to build a release version with the SDK we get this error:

> Undefined symbols for architecture armv7:
>   "_OBJC_CLASS_$_GSKScannerUI", referenced from:
>       objc-class-ref in libRNGeniusScan.a(RNGeniusScan.o)
>   "_OBJC_CLASS_$_GSKScannerUIConfiguration", referenced from:
>       objc-class-ref in libRNGeniusScan.a(RNGeniusScan.o)
>   "_OBJC_CLASS_$_GSK", referenced from:
>       objc-class-ref in libRNGeniusScan.a(RNGeniusScan.o)
> ld: symbol(s) not found for architecture armv7

When I build in debug, it works.
We are using @thegrizzlylabs/react-native-genius-scan - 3.0.8 and react-native 0.59.10.
Any ideas?

**Comment by guillaume-tgl** [comment]
Our SDK doesn't support armv7 because the minimum iOS version we support is iOS 11.
This chart gives the correspondance between iOS versions and architectures: https://www.facebook.com/iossupportmatrix/photos/a.615711035125738/1801697649860398/?type=1&theater
You need to set the default target to iOS 11.

**Comment by felix-zg** [comment]
@guillaume-tgl  Thanks!

**Comment by spyx08** [comment]
Hello,

I've same issue trying to build a release with iOS 14.3

> Undefined symbols for architecture x86_64:
>   "_OBJC_CLASS_$_GSKScanFlow", referenced from:
>       objc-class-ref in GeniusScan.o
>   "_OBJC_CLASS_$_GSKScanFlowConfiguration", referenced from:
>       objc-class-ref in GeniusScan.o
>   "_OBJC_CLASS_$_GSK", referenced from:
>       objc-class-ref in GeniusScan.o
> ld: symbol(s) not found for architecture x86_64

**Comment by bvirlet** [comment]
Hello,
It's a different issue, linked to Capacitor. We're investigating and we'll reply to your email support request as soon as we have a workaround.
