### ISSUE TITLE
Disable auto detect of document when scanning?

### ISSUE THREAD

**Issue by nirpeled** [thegrizzlylabs/geniusscan-sdk-demo#20]
Is it possible to disable the auto detection of a document when scanning?

**Comment by guillaume-tgl** [comment]
If you use the UI module or a crossplatform plugin we provide, no, it's not possible to disable it. Did you or your users have trouble with it?

**Comment by nirpeled** [comment]
I use the react native SDK and it's not very stable UX-wise 😞

**Comment by msoltany** [comment]
> If you use the UI module or a crossplatform plugin we provide, no, it's not possible to disable it. Did you or your users have trouble with i

**Comment by umerchaudhary34** [comment]
@nirpeled have you got any solution how to disable auto detect of document?

**Comment by bvirlet** [comment]
@umerchaudhary34 are you having trouble with the auto-detection? Version 4 should have solved most problems. Which version of the SDK are you using?

**Comment by umerchaudhary34** [comment]
@bvirlet no i just dont want that auto detectection.I want that when user capture the image then it should detect the object and then take it to the cropping option.can you we that @bvirlet ?

**Comment by guillaume-tgl** [comment]
Unfortunately, that's not possible with the ScanFlow integration. But you can use our Core module to create your own UX: https://geniusscansdk.com/docs/v4/overview/#custom-integration-with-the-core-module
