### ISSUE TITLE
React Native localization

### ISSUE THREAD

**Issue by famaranon** [thegrizzlylabs/geniusscan-sdk-demo#28]
Hi!

We've recently purchased a license and I'm integrating the SDK in our app.

The app is intended to be localized only in Spanish (Chile). Android integration went smoothly and the text is translated to Spanish correctly.
However, we can't make it work correctly in IOS. I am testing in a device set up in Spanish (Chile) and the scanner text still appears in English.

I tried adding localization options in Xcode as stated in the plugin documentation (as shown in the picture) but it has not worked.

<img width="466" alt="Screen Shot 2020-06-03 at 17 32 54" src="https://user-images.githubusercontent.com/11680615/84290452-accaff80-ab11-11ea-8623-c8e876e3e4d2.png">

What can I do to fix this issue?. Or even better, is there a way to force the language of the plugin to always be Spanish, ignoring device settings?.

Thanks for your support

**Comment by bvirlet** [comment]
Hi @famaranon. I'm trying to reproduce the problem but without success. 

The framework will always use the localization of the main app, but if localization is not properly enabled for the app, then it will fall back to English.

What's strange in your screenshot is that it says "0 Files Localized". When you added the `Spanish (Chile)` language to the project, you must have selected some file to localize (for instance LaunchScreen.storyboard). I think there must be at least one file localized in your project for the language to be properly picked up. 

What I would recommend:
- Remove all Spanish localizations from this screen, re-add them, making sure you localize at least one file.
- You can also use the React Demo App (make sure it's a clean install) and add the `Spanish (Chile)` localization. You will see that the Genius Scan SDK properly picks up the language.

**Comment by JaimePata** [comment]
Hi @bvirlet 
Thanks! The problem was the one you mentioned, we needed to localize at least one file in order to make it work correctly.

**Comment by bvirlet** [comment]
Thanks for the update!

**Comment by LudoLamerre** [comment]
Hi,

I try to switch the RN sdk to french, but when I click on + in Xcode there is already 0 Files localized.
How can I do to add french local ?

Thank you in advance.

**Comment by guillaume-tgl** [comment]
@LudoLamerre Did you see [this comment](https://github.com/thegrizzlylabs/geniusscan-sdk-demo/issues/28#issuecomment-642481983) from Bruno?

**Comment by LudoLamerre** [comment]
Yes I saw the comment but I didn't add localized file in my .storyboard 😅.
Thank you.

**Comment by leonardoballand** [comment]
Hi,

We also use the Genius Scan SDK, and our users can change app language in a settings screen. Would we be able to update Genius Scan SDK language on the fly?
