### ISSUE TITLE
Rendering-Problem on Android-Device(s)

### ISSUE THREAD

**Issue by SaschaA1982** [thegrizzlylabs/geniusscan-sdk-demo#29]
Hi everyone.

When I run the flutter demo project on an android devide some controls "flow" out of screen:

![Selection_013](https://user-images.githubusercontent.com/19424417/85022113-1fbc2200-b173-11ea-93dc-e3697d4d4709.png)

Am I usind it wrong, is it a bug or expected behaviour?

On iOS everything works fine...

Thanks.

**Comment by guillaume-tgl** [comment]
Do you get this issue only on this device or on other Android devices too? We're aware of a bug on devices with a 16:9 camera and we're currently fixing it so it could be the issue.

**Comment by SaschaA1982** [comment]
I am facing the problem on my Samsung Galaxy S6 and my Huawei Honor 9.

**Comment by SaschaA1982** [comment]
@guillaume-tgl 
Getting better with version 3.0.19:

![image](https://user-images.githubusercontent.com/19424417/85758950-0f76ea80-b711-11ea-9837-daee7b91e5a9.png)

Would be nice if camera preview would be in full width of the screen...
