### ISSUE TITLE
Question: custom labels possible

### ISSUE THREAD

**Issue by SaschaA1982** [thegrizzlylabs/geniusscan-sdk-demo#32]
Hi everyone.

We are looking for the possibility to provide custom labels to the flutter plugin for the GeniusScanSDK.

Is it possible to do so and if yes, how could we achieve that?

Thanks!

**Comment by bvirlet** [comment]
Thanks for your request. Are there some specific labels that you would like to customize?

**Comment by SaschaA1982** [comment]
My testers told me, that there is at least one label that does not fit the german language properly... It is the label for "stop moving your device". I don't know if they will criticise more than this label. 

So I think it would be great, if all of the labels which where presented towards the user could be customized. Maybe by "hijacking" the localization?

**Comment by bvirlet** [comment]
@SaschaA1982 we'll consider adding the ability to customize the text in a future update of the SDK. For now it's not possible. Can you however let us know about what strings are incorrect? We will make sure to fix that quickly.

**Comment by SaschaA1982** [comment]
@bvirlet My tester criticise the label "Bitte stabil bleiben". In our opinion a better translation for this label would be "Bitte Gerät ruhig halten".

**Comment by bvirlet** [comment]
The translation will be fixed in SDK 3.0.22 to be released later today.
