### ISSUE TITLE
backbone.png & head_classif.png taking up 6Mb in assets folder

### ISSUE THREAD

**Issue by amir-dropit** [thegrizzlylabs/geniusscan-sdk-demo#41]
In version 4.0.1 of the android sdk there are two png files that are adding about 6mb to every app download from the store, even if using app bundles.

![image](https://user-images.githubusercontent.com/71273519/112843454-436daa80-90ab-11eb-8236-3eac8a5a2ce6.png)

Is this really necessary?

**Comment by guillaume-tgl** [comment]
Despite their extension, these files are not images. They are necessary for the document detection.
