### ISSUE TITLE
White screen on IOS

### ISSUE THREAD

**Issue by kmkrtich** [thegrizzlylabs/geniusscan-sdk-demo#43]
Only on first install of the application I'm facing white screen on IOS.
I.e. I accept all permissions that it is asking, then it goes to the white screen.
But if I close then reopen application again it will work.

ReactNative - 0.63.3
react-native-genius-scan - 4.0.8
iPhone 6
IOS version - 12.5.3

**Comment by guillaume-tgl** [comment]
Thanks for the details. Do you experience this issue with your own app or with our demo app?
Is there any way you could send us a video showing this?

**Comment by kmkrtich** [comment]
It happens on my own application. I can't test it with demo application because it requires IOS >= 13.0

**Comment by guillaume-tgl** [comment]
The deployment target seems to be set to iOS 11. Where do you see it requires iOS 13?

**Comment by kmkrtich** [comment]
![Image from iOS](https://user-images.githubusercontent.com/48594915/122184111-f4ab0200-ce9c-11eb-8ced-2908220f8386.jpg)

**Comment by guillaume-tgl** [comment]
Oh, I meant our ReactNative demo app available in this repository, not Genius Scan: https://github.com/thegrizzlylabs/geniusscan-sdk-demo/tree/master/react-native-genius-scan-demo

**Comment by guillaume-tgl** [comment]
@kmkrtich did you find a way to solve this issue? Could you tell us more about what was wrong?
