### ISSUE TITLE
License key is not working in ios and getting this error.

### ISSUE THREAD

**Issue by HarshilVaghasiya** [thegrizzlylabs/geniusscan-sdk-demo#58]
![Screenshot 2022-11-02 at 6 21 54 PM](https://user-images.githubusercontent.com/100259335/199494807-67647e92-c0d8-4730-9027-c2ab26bf0187.png)

**Comment by HarshilVaghasiya** [comment]
I'm using this library in react-native.
In IOS I am getting this error while setting the license with the key.
In android with react-native, it is working well.

**Comment by guillaume-tgl** [comment]
Have you run `pod install` from the iOS folder?

**Comment by HarshilVaghasiya** [comment]
Yes, I installed it. But get the same error.

**Comment by guillaume-tgl** [comment]
Have you tried our React Native demo app to see if you can reproduce your issue?

**Comment by aliza-khu** [comment]
Hey! I also faced this same issue when I update the project from **react native 0.66.5 to 0.70.5**. From Android, it's working fine but on **iOS, it crashes for the same reason**.

**Below is the old project configuration:**

"react": "17.0.2",
"react-native": "0.66.5",
"@thegrizzlylabs/react-native-genius-scan": "^4.5.0",

**Below is the latest project configuration:**

"react": "18.1.0",
"react-native": "0.70.5",
"@thegrizzlylabs/react-native-genius-scan": "^4.5.0"

HERMES: ON,
NEW ARCHITECTURE(Turbo Modules & Fabric): OFF

I also try to update the "@thegrizzlylabs/react-native-genius-scan" but it won't work.
I also refer to the deme app of the same library and found that it's using the below config:

"@thegrizzlylabs/react-native-genius-scan": "^4.7.1",
"react": "17.0.2",
"react-native": "0.66.0",

Can you please share the **assumption data for this issue to be fixed** with the new version of the @thegrizzlylabs/react-native-genius-scan library? Or Anyone has a solution for this issue using a **patch file** or something like that? I found this is the only reason I won't able to use the react native latest version.

**Comment by TrevorMCS** [comment]
Running into as well after upgrading from 0.68.0 => 0.70.5

"@thegrizzlylabs/react-native-genius-scan": "^4.7.1",
"react": "18.2.0",
"react-native": "0.70.5",

**Comment by guillaume-tgl** [comment]
This should be fixed by v4.7.2 of our SDK. Let us know if it works.
