### ISSUE TITLE
GSSDKCore does not contain bitcode.

### ISSUE THREAD

**Issue by aliza-khu** [thegrizzlylabs/geniusscan-sdk-demo#59]
I am facing the below error when building the app on iOS.

...Build/Products/Debug-iphoneos/XCFrameworkIntermediates/RNGeniusScan/GSSDKCore.framework/GSSDKCore' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. file '...Build/Products/Debug-iphoneos/XCFrameworkIntermediates/RNGeniusScan/GSSDKCore.framework/GSSDKCore' for architecture arm64.

The ... path is of the derived data folder.

I am using the below config on react native project:

"react": "18.1.0",
"react-native": "0.70.5",
"@thegrizzlylabs/react-native-genius-scan": "^4.7.3",

Temporary solution: 
ENABLE_BITCODE = NO; instead of YES in project.pbxproj file of iOS.

Can the library team provide the updated version with a solution to this?

**Comment by guillaume-tgl** [comment]
We've removed support for bitcode in [v4.6.0](https://geniusscansdk.com/docs/changelog/#460---2022-10-04) of Genius Scan SDK.

Also, bitcode is deprecated (https://developer.apple.com/documentation/Xcode-Release-Notes/xcode-14-release-notes). Apple doesn't even allow submissions containing bitcode, so the future is ENABLE_BITCODE = NO;

**Comment by aliza-khu** [comment]
Okay. Got it. Thank you. 👍
