### ISSUE TITLE
Pick images from gallery

### ISSUE THREAD

**Issue by komritza** [thegrizzlylabs/geniusscan-sdk-demo#63]
Hi,
I am using a flutter sdk and trying to find some options to customise UI/UX. 

Is there a way to add a go to gallery button(or any other button) while being in the camera view? Similar to the normal camera UX where user can access gallery and pick single/multiple images.

Thanks in advance!

**Comment by bvirlet** [comment]
Hi @komritza,

No, it's not possible with the Flutter plugin. If you want to achieve such a behavior, you must wrap the native code.

**Comment by komritza** [comment]
Hi @bvirlet 
thanks for the fast reply! It is petty though, that it must be done through native code.

**Comment by bvirlet** [comment]
@komritza I understand it might not be ideal for you. Can you let us know about your use case so that it informs future evolutions of the scan flow?

**Comment by komritza** [comment]
@bvirlet You can read about use cases here https://github.com/thegrizzlylabs/geniusscan-sdk-demo/issues/62#issuecomment-1351496932
