### ISSUE TITLE
Arabic Scanners is not been opened when my app language in Arabic.

### ISSUE THREAD

**Issue by pavanbol** [thegrizzlylabs/geniusscan-sdk-demo#66]
When my app is in Arabic and when I start the `ScanActivity` in Android it still shows in English not in arabic could you please help me in localising the app for Arabic case as my entire app is in Arabic and the scan flow in English.

**Comment by guillaume-tgl** [comment]
The ScanFlow is localized in Arabic so I'm surprised it's displayed in English. Is your device language set to Arabic?

**Comment by pavanbol** [comment]
No device language is English and we are changing the app language to Arabic.
will that not work if device language is English ?

**Comment by guillaume-tgl** [comment]
No, that won't work. The ScanFlow uses the device language for now.
