### ISSUE TITLE
Button is behind other interface elements

### ISSUE THREAD

**Issue by komritza** [thegrizzlylabs/geniusscan-sdk-demo#69]
We got some feedback from our customer regarding position of the flash button. 

> The button is behind other interface elements. there needs to be more space at the top to prevent 

![david_test_flight](https://user-images.githubusercontent.com/44901103/214587742-f6e59d71-d394-462a-8d96-810e8aa4c7a2.jpeg)

Maybe something to improve from your side. 

GeniusScanVersion: 4.7.4
OS: iOS

**Comment by guillaume-tgl** [comment]
Have you had a look at this troubleshooting section which addresses this issue: https://geniusscansdk.com/docs/v4/ios/troubleshooting/#the-status-bar-appearance-is-broken-in-the-scan-flow ?

**Comment by komritza** [comment]
I didn't see this part. Thank you very much!
