### ISSUE TITLE
App center build is not working with demo license

### ISSUE THREAD

**Issue by test20241988** [thegrizzlylabs/geniusscan-sdk-demo#80]
I'm using trail version key and added licsense key in my app, but I'm getting below error while generate thw build in App center.
error: cannot access GeniusScanSDK
import com.geniusscansdk.core.GeniusScanSDK;

error: cannot access LicenseException
import com.geniusscansdk.core.LicenseException;
But build is working fine in locally, I want to generate the build using App center using pipeline.
Anyone plz help here @guillaume-tgl @adrien-k @bvirlet @jerome-tgl

**Comment by guillaume-tgl** [comment]
Please contact sdk@geniusscan.com for licensing issues.
