### ISSUE TITLE
How to handle the Cancel event

### ISSUE THREAD

**Issue by rajiniyadav** [thegrizzlylabs/geniusscan-sdk-demo#82]
Hello,

I need to handle if user clicked cancel or quit the Genius camera?
I need show some popup/log the data to server.

Could you pls help on this

Thanks

**Comment by guillaume-tgl** [comment]
Do you have a native integration or do you use a crossplatform plugin?
If it's a native integration, for which platform do you need help? Android, iOS, both?

**Comment by rajiniyadav** [comment]
I'm using native android using Java.

**Comment by rajiniyadav** [comment]
Following demo-simple

**Comment by guillaume-tgl** [comment]
Ok, then, you can check if a user cancels a ScanFlow by checking if the `resultCode` is `RESULT_CANCELED` in the `onActivityResult` callback.
Here is where you would check this in the SimpleDemo: https://github.com/thegrizzlylabs/geniusscan-sdk-demo/blob/master/android/demo-simple/src/main/java/com/geniusscansdk/simpledemo/MainActivity.java#L123

**Comment by rajiniyadav** [comment]
Thanks a lot, its works.

**Comment by kristabel-wong** [comment]
i'm using react-native and need to handle a Cancel event. Could you assist please?

**Comment by guillaume-tgl** [comment]
> i'm using react-native and need to handle a Cancel event. Could you assist please?

You can catch the exceptions from `RNGeniusScan.scanWithConfiguration` and check if the error code is `E_SCAN_CANCELED`
