### ISSUE TITLE
How to pass image to geniusscansdk in flutter?

### ISSUE THREAD

**Issue by abdallah-odeh** [thegrizzlylabs/geniusscan-sdk-demo#84]
I am trying to process an image selected from gallery with Genius scan, but the plugin returns the following error:

`PlatformException(GSKErrorDomain error 1003, Input image cannot be nil, null, null)`

I assume that I implemented this correctly according to the documentation written in the code:

```
  /// * `source`: `camera`, `image` or `library` (defaults to camera)
  /// * `sourceImageUrl`: an absolute image url, required if `source` is `image`. Example: `file:///var/…/image.png`

      var result = await FlutterGeniusScan.scanWithConfiguration({
        'source': 'image',
        'sourceImageUrl': imagePath,
        'defaultFilter': 'photo',
      });
```

I also thought maybe the file itself does not exists so I checked that out by:

```
  print('IS FILE EXIST? ${await File(imagePath).exists()}');
  // and got in the log:
  flutter: IS FILE EXIST? true
```

so how to pass an image to process it?

**Comment by bvirlet** [comment]
Can you print `imagePath` ?

**Comment by abdallah-odeh** [comment]
It seems I had issue with the license key, issue solved.
thank you so much
