### ISSUE TITLE
[React Native] IOS - Camera green LED

### ISSUE THREAD

**Issue by ilatour-dino** [thegrizzlylabs/geniusscan-sdk-demo#89]
Hi
is it normal that after scanning a document and closing the camera, the camera's green LED remains active forever?

react-native: 0.74.0
@thegrizzlylabs/react-native-genius-scan: 5.1.0
Device: Iphone 15 pro 17.5.1

**Comment by bvirlet** [comment]
Hi there, we are investigating this issue but are having trouble consistently reproducing it. We'll let you know once we have a fix.

**Comment by guillaume-tgl** [comment]
Yes, here is the full changelog of the latest version: https://geniusscansdk.com/docs/changelog/
Let us know if everything is working correctly for you.
