### ISSUE TITLE
[React Native] iOS - Booting Doc Scanning From Landscape Causes Camera Orientation To Be Stuck

### ISSUE THREAD

**Issue by andrew-nguyen-mcs** [thegrizzlylabs/geniusscan-sdk-demo#90]
Whenever we boot from landscape, the camera will be stuck in portrait mode even though the device is in landscape.  It doesn't behave the same on android as the take picture button and cancel button will just stay anchored to one spot.  Instead the take picture button and the cancel button will rotate.

iOS (holding the tablet in landscape and the buttons are at the bottom)
![image](https://github.com/user-attachments/assets/dea42f0a-22db-4016-aa41-04c89ad5dd82)
When rotating to portrait, the camera will stay stuck in this orientation ^

**Comment by thomas4Bitcraft** [comment]
@andrew-nguyen-mcs did you manage to start the camera on Android in landscape mode?

**Comment by guillaume-tgl** [comment]
> @andrew-nguyen-mcs did you manage to start the camera on Android in landscape mode?

The camera screen in the ScanFlow module (and in the ReactNative plugin) is restricted to portrait on Android. Feel free to create another issue if you need the camera to be displayed in landscape mode.
